/****** Script for SelectTopNRows command from SSMS  ******/
WITH A AS (
SELECT  [CLAIM_NO]
	  ,[POLICY_NUMBER]
      ,[AGENT_CODE]
	  ,[CLM_SUBMIT_DATE] 
	  --,[AD_NAME]
	  ,[AGENT_CODE] + CONVERT(CHAR(6), [CLM_SUBMIT_DATE], 112) AS ID
  FROM [PowerBI].[DPO].[CLAIM]
  --GROUP BY [POLICY_NUMBER]
 -- WHERE [PAYMENT_NOTICED] IS NULL
 )

 ,B AS (
SELECT  B.Agent_Number
		,MIN(B.ID) AS ID
  FROM [PowerBI].[DPO].[Main_AGENCY_STRUCTURE] AS B
  GROUP BY B.Agent_Number
  --GROUP BY [POLICY_NUMBER]
 -- WHERE [PAYMENT_NOTICED] IS NULL
 )

,C AS (
SELECT 
	A.*
	, IIF(HOT_FIX.ID > A.ID, HOT_FIX.ID, A.ID) AS ID2
	--,E.AD_Code
	--, D.[Current Agent]
FROM A
LEFT JOIN B AS HOT_FIX
ON A.AGENT_CODE = HOT_FIX.Agent_Number
)

SELECT
	C.CLAIM_NO
	,C.POLICY_NUMBER
	,C.AGENT_CODE
	,C.CLM_SUBMIT_DATE
	,C.ID2 AS ID
	,E.AD_Code
	,E.ID_AD
	--,AD.ADName AS ADNAME2
	,E.AD_Code_Current
	,E.ID_AD_Current
	--,AD2.ADName AS ADNAME3
FROM C
LEFT JOIN [PowerBI].[DPO].[Main_AGENCY_STRUCTURE] AS E
ON C.ID2 = E.ID

LEFT JOIN [PowerBI].[DPO].Main_AD_STRUCTURE_FULL AS AD
ON E.ID_AD = AD.ID

LEFT JOIN [PowerBI].[DPO].Main_AD_STRUCTURE_FULL AS AD2
ON E.ID_AD_Current = AD2.ID

--WHERE C.AD_NAME = AD2.ADName

 --LEFT JOIN [PowerBI].[DPO].[DP_AGPOLTRANSFER] AS D
 --ON A.POLICY_NUMBER = D.CHDRNUM
 --AND D.[Old Agent Effect From ] <= A.CLM_SUBMIT_DATE AND D.[Current Agent Effect From] < A.CLM_SUBMIT_DATE
