SELECT * FROM [dbo].[DP_TAGENTPREMIUM_TEST]
WHERE [Policy No] = '80073425'

SELECT * FROM [dbo].[DP_TDAILYSALES_DA]
WHERE [POLICY_NUMBER] = '80073425'

SELECT * FROM [dbo].[Main_POLICY_INFO]
WHERE [POLICY_NUMBER] = '80073425'



SELECT * FROM [DPO].[view_Detail]