SELECT [Policy No], [Product Code], [Premium transaction], [PREM TRAN NAME], [Premium Collected], [Collected Date], [Applied Premium Date], [FYP Before Discount], [FYP Discount], FYP, RYP, [Topup Premium], [Premium Term], [Premium Year], [Policy Status], [Policy Year], [Policy Term], 
             [Frequency of Payment], [Issued Date], [Effected Date], [Terminated Date], [Lapse Date], [Due date], [Next Due Date], [Transfer Date], [POLICY ACKNOWLED], [Sum Assure], [Area Code], [Servicing Agent], Freelook, [Proposal Receive Date], RISK_COMMENCE_DATE, Age_Customer, 
             [Issuing Agent], AFYP, Policy_Number, [Contract Type], Frequency, CASE WHEN (YEAR([Issued Date]) = YEAR([Collected Date]) AND MONTH([Issued Date]) = MONTH([Collected Date])) THEN (([FYP] / Frequency) + ([Topup Premium] * 0.1)) WHEN (YEAR([Issued Date]) 
             <> YEAR([Collected Date]) AND MONTH([Issued Date]) <> MONTH([Collected Date]) AND ([Policy Status] = 'FL')) THEN (([FYP] / Frequency) + ([Topup Premium] * 0.1)) WHEN (([Issued Date] IS NULL) AND [Policy Status] IN ('DC', 'PO')) THEN ([FYP] + ([Topup Premium] * 0.1)) 
             ELSE 0 END AS AFYP_new
FROM   (SELECT [Policy No], [Product Code], [Premium transaction], [PREM TRAN NAME], [Premium Collected], [Collected Date], [Applied Premium Date], [FYP Before Discount], [FYP Discount], FYP, RYP, [Topup Premium], [Premium Term], [Premium Year], [Policy Status], [Policy Year], 
                           [Policy Term], [Frequency of Payment], [Issued Date], [Effected Date], [Terminated Date], [Lapse Date], [Due date], [Next Due Date], [Transfer Date], [POLICY ACKNOWLED], [Sum Assure], [Area Code], [Servicing Agent], Freelook, [Proposal Receive Date], 
                           RISK_COMMENCE_DATE, Age_Customer, [Issuing Agent], AFYP, Policy_Number, [Contract Type], CASE WHEN (c.[Contract Type] NOT LIKE 'UL%' AND [Frequency of Payment] = 'Yearly') THEN 1 WHEN (c.[Contract Type] NOT LIKE 'UL%' AND 
                           [Frequency of Payment] = 'Half-year') THEN 0.53 WHEN (c.[Contract Type] NOT LIKE 'UL%' AND [Frequency of Payment] = 'Quarterly') THEN 0.27 WHEN (c.[Contract Type] NOT LIKE 'UL%' AND [Frequency of Payment] = 'Monthly') 
                           THEN 0.09 WHEN (c.[Contract Type] LIKE 'UL%' AND [Frequency of Payment] = 'Yearly') THEN 1 WHEN (c.[Contract Type] LIKE 'UL%' AND [Frequency of Payment] = 'Half-year') THEN 0.5 WHEN (c.[Contract Type] LIKE 'UL%' AND [Frequency of Payment] = 'Quarterly') 
                           THEN 0.25 END AS Frequency
             FROM    (SELECT a.[Policy No], a.[Product Code], a.[Premium transaction], a.[PREM TRAN NAME], a.[Premium Collected], a.[Collected Date], a.[Applied Premium Date], a.[FYP Before Discount], a.[FYP Discount], a.FYP, a.RYP, a.[Topup Premium], a.[Premium Term], a.[Premium Year], 
                                         a.[Policy Status], a.[Policy Year], a.[Policy Term], a.[Frequency of Payment], a.[Issued Date], a.[Effected Date], a.[Terminated Date], a.[Lapse Date], a.[Due date], a.[Next Due Date], a.[Transfer Date], a.[POLICY ACKNOWLED], a.[Sum Assure], a.[Area Code], 
                                         a.[Servicing Agent], a.Freelook, a.[Proposal Receive Date], a.RISK_COMMENCE_DATE, a.Age_Customer, a.[Issuing Agent], a.AFYP, b.Policy_Number, b.[Contract Type]
                           FROM    DPO.view_DP_TAGENTPREMIUM_TEST_PS AS a LEFT OUTER JOIN
                                             (SELECT DISTINCT Policy_Number, [Contract Type]
                                             FROM    dbo.DP_TDAILYSALES_DA) AS b ON a.[Policy No] = b.Policy_Number) AS c) AS q