SELECT DISTINCT a.*,
		b.[NAME_AD]
FROM 
	(SELECT [CODE_AD], [NAME_AD], 
		IIF ([CODE_RD] IS NOT NULL, [CODE_RD], 
			IIF ([CODE_TD] IS NOT NULL, [CODE_TD], NULL))  AS PARENT_CODE
	FROM [dbo].[Main_AD_STRUCTURE] ) a
JOIN [dbo].[Main_AD_STRUCTURE] b
ON b.[CODE_AD] = a. PARENT_CODE
	
SELECT * FROM [Main_AD_STRUCTURE] 

WHERE [GRADE] = 'TD'

		