
USE [PowerBI]
GO

/****** Object:  View [DPO].[Cal_AD_K2]    Script Date: 6/29/2021 1:09:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER VIEW [DPO].[Cal_AD_K2]
AS
SELECT A.Area_Name AS Area_Name, A.Sales_Unit_Code AS Sales_Unit_Code,[Sales_Unit] AS AD, K.[AGENT NO], K.[POLICY NO], K.LIFE, K.COMPONENT, K.RCD, K.[Effected Date], K.PTD, K.FREQUENCY, K.[COMPONENT STATUS], K.[Y2 ACTUAL PREM], K.[Y2 EXPECTED PREM]
FROM   DPO.DP_K2 AS K 
--LEFT JOIN [PowerBI].[DPO].[Main_POLICY_INFO] AS P 
--ON K.[POLICY NO] = P.[POLICY_NUMBER]

LEFT OUTER JOIN [DPO].Main_AGENT_INFO_DA AS A ON K.[AGENT NO] = A.Agent_Number
GO